//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Songs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLEXPRESS;Initial Catalog=songbook;Integrated Security=Tru" +
            "e;Encrypt=False")]
        public string LocalSongbookConnection {
            get {
                return ((string)(this["LocalSongbookConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=speepmaster\\SQLEXPRESS;Initial Catalog=Songbook;Integrated Security=T" +
            "rue;TrustServerCertificate=True")]
        public string LocalSpeepmasterSongbookConn {
            get {
                return ((string)(this["LocalSpeepmasterSongbookConn"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Dietrich\\Music\\LYRICS\\MobilesheetsTest")]
        public string MobilesheetsNoLyricsDirectory {
            get {
                return ((string)(this["MobilesheetsNoLyricsDirectory"]));
            }
            set {
                this["MobilesheetsNoLyricsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Dietrich\\Music\\LYRICS\\TabletPDFs")]
        public string LyricPDFsDirectory {
            get {
                return ((string)(this["LyricPDFsDirectory"]));
            }
            set {
                this["LyricPDFsDirectory"] = value;
            }
        }
    }
}
