// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCoreSongs.Models;

public partial class Alternateartists
{
    public int Id { get; set; }

    public int SongId { get; set; }

    public int ArtistId { get; set; }

    public virtual Artists Artist { get; set; }
}