// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebCoreSongs.Models;

public partial class ArtistsContext : DbContext
{
    public ArtistsContext(DbContextOptions<ArtistsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Artists> Artists { get; set; }

    public virtual DbSet<Venues> Venues { get; set; }

    public virtual DbSet<Viewartistnameforlistbox> Viewartistnameforlistbox { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Artists>(entity =>
        {
            entity.HasKey(e => e.ArtistId).HasName("PK_artists_ArtistID");

            entity.ToTable("artists", "songbook");

            entity.Property(e => e.ArtistId).HasColumnName("ArtistID");
            entity.Property(e => e.ArtistFirstName).IsUnicode(false);
            entity.Property(e => e.ArtistLastName).IsUnicode(false);
        });

        modelBuilder.Entity<Venues>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_venues_ID");

            entity.ToTable("venues", "songbook");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Comment)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Viewartistnameforlistbox>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("viewartistnameforlistbox", "songbook");

            entity.Property(e => e.Artist).ValueGeneratedOnAdd();
            entity.Property(e => e.ArtistFirstName).IsUnicode(false);
            entity.Property(e => e.ArtistLastName).IsUnicode(false);
            entity.Property(e => e.Name).IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}