// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCoreSongs.Models;

public partial class Performances
{
    public int Id { get; set; }

    public DateOnly PerformanceDate { get; set; }

    public int Venue { get; set; }

    public string Comment { get; set; }

    public int? Series { get; set; }

    public string PerformanceType { get; set; }

    public bool DidIlead { get; set; }
}