// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCoreSongs.Models;

public partial class Songperformances
{
    public int Id { get; set; }

    public int Performance { get; set; }

    public int Song { get; set; }

    public string Comment { get; set; }
}