// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations; 

namespace WebCoreSongs.Models;

public partial class Venues
{
    // only put Key in, on 2/22/24, because it was saying the selectlist didn't have a key
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }

    public string Comment { get; set; }
}