// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCoreSongs.Models;

public partial class Venues
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Comment { get; set; }


    // static ctor, for select lists
    // TODO this s/ probly go into a non-generated sep module
    static Venues()
    {
        _SelectRow = new Venues();
        _SelectRow.Id = -1;
        _SelectRow.Name = " -- Select -- ";
    }

    // special pseudo-rows:
    public static Venues _SelectRow;
}