// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCoreSongs.Models;

public partial class Venues
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Comment { get; set; }
}