// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCoreSongs.Models;

public partial class Viewartistnameforlistbox
{
    public string Name { get; set; }

    public string ArtistLastName { get; set; }

    public int Artist { get; set; }

    public string ArtistFirstName { get; set; }
}