// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebCoreSongs.Models;

public partial class Viewsongperformances
{
    public int PerformanceId { get; set; }

    public int Song { get; set; }

    public string Comment { get; set; }

    public string PerfComment { get; set; }

    public string TitleAndArtist { get; set; }

    public DateOnly PerformanceDate { get; set; }

    public bool DidIlead { get; set; }

    public int? PerformanceYear { get; set; }

    public string PerformanceQtr { get; set; }

    public string PerformanceMonth { get; set; }

    public string VenueName { get; set; }

    public int Venue { get; set; }

    public int PerfID { get; set; }

    public int SongPerfID { get; set; }
}