// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace WebCoreSongs.Models;

public partial class Viewsongperformances
{
    public int PerformanceId { get; set; }

    public int Song { get; set; }

    public string Comment { get; set; }

    public string TitleAndArtist { get; set; }

    public DateOnly PerformanceDate { get; set; }

    public bool DidIlead { get; set; }

    public int? PerformanceYear { get; set; }

    public string PerformanceQtr { get; set; }

    public string PerformanceMonth { get; set; }

    public string VenueName { get; set; }

    public int Venue { get; set; }

    // This is to populate Venues dropdown listbox, per https://stackoverflow.com/questions/59601041/populate-dropdownlist-using-ef-core-from-another-model.
    // That website has a couple more ideas about how to do this simply.
    public IEnumerable<SelectListItem> Venues { get; set; } 
}