// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebCoreSongs.Models;

public partial class Viewsongssinglefield
{
    public string SongFull { get; set; }

    public string TitleAndInfo { get; set; }

    public string TitleAndArtist { get; set; }

    public string FullTitle { get; set; }

    public string SongFullArtistFirst { get; set; }

    public string SongInfo { get; set; }

    public string ArtistFirstName { get; set; }

    public string ArtistLastName { get; set; }

    public string FullArtistName { get; set; }

    public string Title { get; set; }

    public string TitlePrefix { get; set; }

    [Key]
    public int Id { get; set; }

    public string Code { get; set; }

    public string PageNumber { get; set; }

    public bool InTablet { get; set; }

    public int Cover { get; set; }
}